name: AWSSDK.SQS.Extensions Build
on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  publish:
    name: Publish Nuget Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
            7.0.x

      - name: Show dotnet info
        run: dotnet --info

      - name: Unit Test
        run: dotnet test --verbosity quiet

      - name: Build with dotnet
        run: dotnet pack ./src/AWSSDK.SQS.Extensions/AWSSDK.SQS.Extensions.csproj -o ./packages/ -c Release
        shell: bash

      - name: Publish nuget
        run: |
          for f in ./packages/*.nupkg
          do
            dotnet nuget push $f --api-key ${{ secrets.NuGetApiKey}} --source https://api.nuget.org/v3/index.json
          done
        shell: bash
