name: AWSSDK.SQS.Extensions Build
on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - run: dotnet --info
      - if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: dotnet test --verbosity quiet

  publish:
    needs: build
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x', '6.0.x', '7.0.x' ]
    name: Publish Nuget Packages
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build with dotnet
        run: ./NuGetPack.bat
        shell: bash

      - name: Publish nuget
        run: |
          for f in ./packages/*.nupkg
          do
            dotnet nuget push $f --api-key ${{ secrets.NuGetApiKey}} --source https://api.nuget.org/v3/index.json
          done
        shell: bash
